### ISSUE TITLE
没有找到disk.img

### ISSUE THREAD

**Issue by AprilWinds** [hurley25/Hurlex-II#10]
我用dd制作了一个新的disk.img，启动后无法输入命令，请问支持的命令是什么？

**Comment by hurley25** [comment]
没看懂你的问题

**Comment by AprilWinds** [comment]
make qemu 命令不是要指定disk.img， 仓库中并没有这个文件

**Comment by hurley25** [comment]
qemu 自己生成一个就行（qemu-img 命令），因为时间和精力，本仓库其实没有完全实现 FS 相关的东西，可以参考 xv6 或者其他资料

**Comment by AprilWinds** [comment]
谢谢
