### ISSUE TITLE
floppy.img没有找到

### ISSUE THREAD

**Issue by namespace-io** [hurley25/Hurlex-II#4]
软盘镜像没有找到 James的那个链接也挂了 看了网上的感觉不太靠谱 请问有标准的吗?

**Comment by namespace-io** [comment]
![1](https://user-images.githubusercontent.com/29119076/27760673-d9115ddc-5e7f-11e7-9334-5f53ab570f0c.png)
对了 我运行起来是这样的 没有Hello world = =

**Comment by hurley25** [comment]
James 那个就行，或者这个 https://github.com/hurley25/hurlex-doc/blob/master/code/chapt3/floppy.img
