### ISSUE TITLE
lib中memspy的内存重叠问题

### ISSUE THREAD

**Issue by homer12** [hurley25/Hurlex-II#7]
https://github.com/hurley25/Hurlex-II/blob/6bb76f89d90bb49039a992d14324b38c6f998c91/lib/string.c#L21

您好，我在你的网站上看到lib中的一些函数实现，我注意到如果 [src,src+len) 与 [dst,dst+len) 发生重叠的话可能会出错。

**Comment by hurley25** [comment]
memcpy 需要使用者自己保证，可能重叠的情况下按照C库标准是使用 memmove （尚未添加）
